# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PLC_Project/PLC_Project.cache/wt [current_project]
set_property parent.project_path D:/PLC_Project/PLC_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/PLC_Project/PLC_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/PLC_Project/PLC_Project.srcs/sources_1/new/FA.vhd
  D:/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_2x2.vhd
  D:/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_4bit.vhd
  D:/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_4x4.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top accMult_4x4 -part xc7k70tfbv676-1


write_checkpoint -force -noxdef accMult_4x4.dcp

catch { report_utilization -file accMult_4x4_utilization_synth.rpt -pb accMult_4x4_utilization_synth.pb }
