# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.cache/wt [current_project]
set_property parent.project_path C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/FA.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_4bit.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_2x2.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_8bit.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_4x4.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_16bit.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_8x8v1.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_32Bits.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/accMult_16x16.vhd
  C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.srcs/sources_1/new/MAC_acc16.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top MAC_acc16 -part xc7k70tfbv676-1


write_checkpoint -force -noxdef MAC_acc16.dcp

catch { report_utilization -file MAC_acc16_utilization_synth.rpt -pb MAC_acc16_utilization_synth.pb }
