# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/FA.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_4bit.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/UDM.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_16bit.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/SkipADD_16bit.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/multiplierapprox88.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/SkipAdd_32bit.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/MAC_Aprrox2x2.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/approxMult_16x162x2.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_33bits.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Adder_34bits.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Act_16bits.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/MAC_approx162x2.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/HiddenNeuron_approx2x2.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/new/Act_32bits.vhd}
  {C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/sources_1/imports/new/NeuralNetw_approx2x2.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/constrs_1/imports/Xillinx/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.srcs/constrs_1/imports/Xillinx/Basys3_Master.xdc}}]


synth_design -top NeuralNetw_approx2x2 -part xc7k70tfbv676-1


write_checkpoint -force -noxdef NeuralNetw_approx2x2.dcp

catch { report_utilization -file NeuralNetw_approx2x2_utilization_synth.rpt -pb NeuralNetw_approx2x2_utilization_synth.pb }
