webtalk_init -webtalk_dir C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 01 00:39:31 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2f838360-1cb2-4026-bb32-144956acd882" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1ba1becea8d54226a7bdd09e5cea07b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "48" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "168 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "1990 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "19779" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "64853" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "25409" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "4.91_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "316848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3878717436 -regid "" -xml C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Bassem/Documents/GitHub/PLC Project/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
