webtalk_init -webtalk_dir C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 29 16:34:31 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1bd9070b-aacb-4609-8c76-efb0a1009e60" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1ba1becea8d54226a7bdd09e5cea07b9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "29" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "132 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "698 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "10900" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "23011" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "7660" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "132364_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1058183123 -regid "" -xml C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Wegdan/Documents/GitHub/PLC_Project/PLC_Project.sim/sim_1/behav/xsim.dir/tb_neuralNetw_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
